### PR TITLE
new ukraine content pack!

### PR DESCRIPTION
**Pull request by baghdadbrian**
These commits establish a new content pack, known as
“t_ukraine_school_cj” There are two new templates, each with it’s own
images. NATHAN- I need you to do the conversion to json and then we
should release a test build of these content packs to see how they
look, in particular whether we need to do any adjustments to the images.

### CODE REVIEW

**Comment by n8fr8** [comment]
This is just the new content, right? It doesn't seem you have added this into any of the content catalog lists so it actually shows up?

**Comment by n8fr8** [comment]
Also, there are no translations, right? It is just what is here, and nothing pulled from transifex?

**Comment by baghdadbrian** [comment]
I'm not sure how to update catalog lists... If you let me know about that I
can be sure to do it in future. I can also ask Steve.

No translation just the content in the pack.

**Comment by n8fr8** [comment]
Is there a new cover image for these?

**Comment by n8fr8** [comment]
Is it this? assets/org.storymaker.app/t_ukraine_school_cj/cover.jpg

**Comment by baghdadbrian** [comment]
Yes, I thought that was the correct place to put the cover image.

**Comment by n8fr8** [comment]
it has to be copied over to the main app assets repo, to be built into the app. thanks!

**Pull request merged**
